### PR TITLE
Refactored HybridQueryPhaseSearcherTests to remove knn specific classes

### PR DESCRIPTION
**Pull request by owaiskazi19**
### Description
Refactored HybridQueryPhaseSearcherTests to remove knn specific classes

### Related Issues
Resolves #https://github.com/opensearch-project/neural-search/issues/859

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by martin-gaievski** [comment]
Code looks good to me, thanks for contribution @owaiskazi19 

I do see other tests where we do have dependency on the same knn classes: https://github.com/opensearch-project/neural-search/blob/main/src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java and https://github.com/opensearch-project/neural-search/blob/main/src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java.

Did you look into those tests as well, can we do similar refactoring?

**Comment by owaiskazi19** [comment]
> Did you look into those tests as well, can we do similar refactoring?

Handled `HybridQueryTests`.  `HybridQueryBuilderTests.java` is tightly coupled with knn and might need another issue of it's own.

**Review by yuye-aws — APPROVED** [review]
Looks good to me

**Comment by minalsha** [comment]
> > Did you look into those tests as well, can we do similar refactoring?
> 
> Handled `HybridQueryTests`. `HybridQueryBuilderTests.java` is tightly coupled with knn and might need another issue of it's own.

@owaiskazi19  could you please create a tracking issue for this if it doesn't exist? Thanks

**Comment by owaiskazi19** [comment]
> @owaiskazi19 could you please create a tracking issue for this if it doesn't exist? Thanks

https://github.com/opensearch-project/neural-search/issues/979

**Pull request merged**
