### PR TITLE
Add reindex ITs

### PR DESCRIPTION
**Pull request by zane-neo**
### Description
Add reindex ITs in neural search

### Issues Resolved
Issue: https://github.com/opensearch-project/neural-search/issues/386

### Check List
- [ ] New functionality includes testing.
    - [ ] All tests pass
- [ ] New functionality has been documented.
    - [ ] New functionality has javadoc added
- [ ] Commits are signed as per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by navneet1v** [comment]
@zane-neo can we add reindex IT for other processors too?

**Comment by navneet1v** [comment]
@zane-neo any update on this PR?

**Comment by zane-neo** [comment]
> @zane-neo can we add reindex IT for other processors too?

The issue in ml-commons is not specific to individual processor, it's more like a generic issue(user info not restored after the listener ran), so one or two processor to cover this is enough I thought.

**Comment by navneet1v** [comment]
> > @zane-neo can we add reindex IT for other processors too?
> 
> The issue in ml-commons is not specific to individual processor, it's more like a generic issue(user info not restored after the listener ran), so one or two processor to cover this is enough I thought.

I won't agree with this. It will be good if we have reindex ITs for atleast all the local model like splade and text embeddings. Text + image processor works on remote model so we cannot integrate here.

**Comment by zane-neo** [comment]
> > > @zane-neo can we add reindex IT for other processors too?
> > 
> > 
> > The issue in ml-commons is not specific to individual processor, it's more like a generic issue(user info not restored after the listener ran), so one or two processor to cover this is enough I thought.
> 
> I won't agree with this. It will be good if we have reindex ITs for atleast all the local model like splade and text embeddings. Text + image processor works on remote model so we cannot integrate here.

This PR already includes splade and text embedding processors.

**Comment by martin-gaievski** [comment]
Using Text_image_embeddings processor with only text field should work with local model. Processor uses mlClient to call the model, and model type is abstracted by the client.

**Comment by zane-neo** [comment]
> Using Text_image_embeddings processor with only text field should work with local model. Processor uses mlClient to call the model, and model type is abstracted by the client.

it's a text embedding case right?

**Comment by martin-gaievski** [comment]
> > Using Text_image_embeddings processor with only text field should work with local model. Processor uses mlClient to call the model, and model type is abstracted by the client.
> 
> it's a text embedding case right?

I think it's not. Embeddings are only text, that's correct, but the processor is text_image. That processor can work with text, image and text+image. If we want to test that reindexing works with all processors it would not be correct to test it with text_embedding and assume that text_image_embedding processor is also tested.

**Comment by zane-neo** [comment]
> > > Using Text_image_embeddings processor with only text field should work with local model. Processor uses mlClient to call the model, and model type is abstracted by the client.
> > 
> > 
> > it's a text embedding case right?
> 
> I think it's not. Embeddings are only text, that's correct, but the processor is text_image. That processor can work with text, image and text+image. If we want to test that reindexing works with all processors it would not be correct to test it with text_embedding and assume that text_image_embedding processor is also tested.

current tests covered local models which can prove the correctness of ml-commons code, no need to add other cases IMO.

**Comment by navneet1v** [comment]
> current tests covered local models which can prove the correctness of ml-commons code, no need to add other cases IMO.

This is not the sole purpose of these tests. If the purpose is for correctness of ML code, the tests should be in MLCommons. 

We want to cover as many use cases as possible in which an ingestion processor can be used. Re-indexing is one of the use-case here. I know we started this PR as part of making sure that bug we got here: https://github.com/opensearch-project/neural-search/issues/386 can be caught in future, but that is not the sole purpose of the tests.

**Comment by zane-neo** [comment]
> > current tests covered local models which can prove the correctness of ml-commons code, no need to add other cases IMO.
> 
> This is not the sole purpose of these tests. If the purpose is for correctness of ML code, the tests should be in MLCommons.
> 
> We want to cover as many use cases as possible in which an ingestion processor can be used. Re-indexing is one of the use-case here. I know we started this PR as part of making sure that bug we got here: #386 can be caught in future, but that is not the sole purpose of the tests.

There're quite a lot different flows/features in OpenSearch, e.g. shrink index, split index, restore index etc. Do we have a way to cover all these features when implementing a new feature to ensure they're not breaking? Is covering only reindex enough?

**Comment by navneet1v** [comment]
> Do we have a way to cover all these features when implementing a new feature to ensure they're not breaking? Is covering only reindex enough?

Given the issue in hand we should start with re-index and then add more case which you provided after this. We can cut a github issue to make sure that we are covering the cases you mentioned too.

**Comment by zane-neo** [comment]
> > Do we have a way to cover all these features when implementing a new feature to ensure they're not breaking? Is covering only reindex enough?
> 
> Given the issue in hand we should start with re-index and then add more case which you provided after this. We can cut a github issue to make sure that we are covering the cases you mentioned too.

Is there already a generic approach to address this? Like which can be used for all plugins so that no need to implement this in individual plugin separately?

**Comment by navneet1v** [comment]
> > > Do we have a way to cover all these features when implementing a new feature to ensure they're not breaking? Is covering only reindex enough?
> > 
> > 
> > Given the issue in hand we should start with re-index and then add more case which you provided after this. We can cut a github issue to make sure that we are covering the cases you mentioned too.
> 
> Is there already a generic approach to address this? Like which can be used for all plugins so that no need to implement this in individual plugin separately?

As per my understanding there is no such thing. Main thing which I was trying to put here was, you are adding ITs only for sparse and text embedding processor. There are other processors too in the plugin. So it will be better if you can add re-index ITs for those processors too.

**Comment by zane-neo** [comment]
Will do more test on open source part to reproduce this issue, will reopen this or create a new PR to this. Closing this now.

**Pull request closed without merging**
