### PR TITLE
[Backport 2.5] Update default setting for integ tests

### PR DESCRIPTION
**Pull request by jmazanec15**
### Description
Manual backport of #104 

### Check List
- [X] Commits are signed as per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by vamshin — APPROVED** [review]
LGTM! Thanks

**Comment by jmazanec15** [comment]
Related: https://github.com/opensearch-project/opensearch-build/issues/2908

**Comment by jmazanec15** [comment]
Appear to be some issues related to Native Memory Circuit Breaker. From test case, Im seeing:
```
error -> Native Memory Circuit Breaker is open, please check your resources!
```

**Comment by ylwu-amzn** [comment]
> Appear to be some issues related to Native Memory Circuit Breaker. From test case, Im seeing:
> 
> ```
> error -> Native Memory Circuit Breaker is open, please check your resources!
> ```

Suggest changing "plugins.ml_commons.native_memory_threshold" to `100`

**Review by ylwu-amzn — APPROVED** [review]

**Pull request merged**
