### PR TITLE
Remove parallelization of get hybridscores

### PR DESCRIPTION
**Pull request by VijayanB**
### Description
This parallelization is not adding any value after comparing the benchmarks with and without this optimization. Hence removing it.

### Check List
- [x] New functionality includes testing.
    - [ ] All tests pass
- [ ] New functionality has been documented.
    - [ ] New functionality has javadoc added
- [ ] Commits are signed as per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by martin-gaievski** [comment]
Can you share rough results of benchmarks, is it the same latency or worse with and without parallel get scores?

**Comment by VijayanB** [comment]
> Can you share rough results of benchmarks, is it the same latency or worse with and without parallel get scores?


Query Count | Vector Count | No of Vector Search Query | No of Term Query | No of Sub-queries | is parallel enabled | K | size | P50 ( client time in ms ) | P90 (  client time in ms ) | P99 ( client time in ms ) |
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
1000 | 50000 | 1 | 1 | 2 | no | 100 | 100 | 101 | 106 | 121 |
1000 | 50000 | 1 | 1 | 2 | yes | 100 | 100 | 101 | 107 | 122 |
1000 | 50000 | 2 | 1 | 3 | no | 100 | 100 | 100 | 108 | 149 |
1000 | 50000 | 2 | 1 | 3 | yes | 100 | 100 | 100 | 108 | 152 |
1000 | 50000 | 1 | 2 | 3 | no | 100 | 100 | 106 | 120 | 200 |
1000 | 50000 | 1 | 2 | 3 | yes | 100 | 100 | 106 | 122 | 205 |

**Comment by VijayanB** [comment]
> Can you share rough results of benchmarks, is it the same latency or worse with and without parallel get scores?

Ran 10 experiments with and without this change, P50 looks same, whereas i see few degradation with P90 and P99 ( in few milliseconds) in 8 out of 10 experiments. This is also consistent with took time.

**Comment by VijayanB** [comment]
I added skip change-log, while merging to main, will group it into 1.

**Review by martin-gaievski — APPROVED** [review]

**Review by naveentatikonda — APPROVED** [review]

**Pull request merged**
