### PR TITLE
Set neural-search plugin 3.0.0 baseline JDK version to JDK-21

### PR DESCRIPTION
**Pull request by reta**
### Description
Set neural-search plugin 3.0.0 baseline JDK version to JDK-21

### Issues Resolved
Closes https://github.com/opensearch-project/neural-search/issues/775

### Check List
- [ ] New functionality includes testing.
    - [x] All tests pass
- [ ] New functionality has been documented.
    - [ ] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@martin-gaievski fyi :-)

**Review by martin-gaievski — APPROVED** [review]

**Review by navneet1v — APPROVED** [review]

**Comment by reta** [comment]
Thanks @martin-gaievski , please note - this is 3.x / main only, no backport is needed

**Comment by martin-gaievski** [comment]
understood, removing 'backport 2.x' label. Is the a plan to move 2.x to 21 at some point?

**Comment by reta** [comment]
> Is the a plan to move 2.x to 21 at some point?

Not a baseline  (== minimum required JDK version), as it would be breaking change

**Pull request merged**
