### PR TITLE
Adding Varun(vibrantvarun) to list of CODEOWNERS

### PR DESCRIPTION
**Pull request by vibrantvarun**
### Description
Adding @vibrantvarun to the list of codeowners 
@opensearch-project/admin

### CODE REVIEW

**Comment by gaiksaya** [comment]
The error is due to missing permissions. Below are the options to solve it:
1. Add @wujunshen with maintainer access
2. If @wujunshen does not want to be a maintainer anymore, please move them to emeritus section in maintainers.md file.

Let me know.
Thanks!

**Comment by vibrantvarun** [comment]
Hi @gaiksaya we have decided to add @wujunshen back in codeowners.

Please give appropriate permissions to @vibrantvarun and @wujunshen.

@opensearch-project/admin

**Comment by martin-gaievski** [comment]
@wujunshen I see you're not actively contributing to this repo https://github.com/opensearch-project/neural-search/graphs/contributors. Do you still want to be a maintainer? Please check error in request above, need to know your answer in order to unblock adding of new person to the list.

**Comment by vibrantvarun** [comment]
Screenshot 2024-02-02 at 11 20 14 AM

**Comment by gaiksaya** [comment]
Added @vibrantvarun with `maintain` access. 
Thanks!

**Comment by vibrantvarun** [comment]
@martin-gaievski I think we can merge this PR now

**Comment by vibrantvarun** [comment]
ACK @martin-gaievski

**Review by martin-gaievski — APPROVED** [review]

**Review by junqiu-lei — APPROVED** [review]

**Pull request merged**
