### PR TITLE
[Backport 2.x] [Feature] Support for Default Model Id 

### PR DESCRIPTION
**Pull request by vibrantvarun**
### Description
Backport [337](https://github.com/opensearch-project/neural-search/pull/337) to 2.x

### Issues Resolved
[70
](https://github.com/opensearch-project/neural-search/issues/70)
### Check List
- [x] New functionality includes testing.
    - [x] All tests pass
- [x] New functionality has been documented.
    - [x] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by navneet1v** [comment]
@vibrantvarun fix the gh actions

**Comment by martin-gaievski** [comment]
@vibrantvarun please check if your PR for core has been backported to 2.x

**Comment by vibrantvarun** [comment]
@martin-gaievski it is backported

**Comment by martin-gaievski** [comment]
discussed with @vibrantvarun, so his PR in core got merged after core incremented 2.x version to 2.11. For his change to work we need to increment version in neural-search, that is typically done by auto-generated PR from infra script.

**Review by navneet1v — APPROVED** [review]

**Review by martin-gaievski — APPROVED** [review]

**Pull request merged**
