### PR TITLE
Fix: typo for sparse encoding processor factory

### PR DESCRIPTION
**Pull request by yuye-aws**
### Description

Fix typo for sparse encoding processor factory

### Issues Resolved

Fix: typo for sparse encoding processor factory

### Check List
- [ ] New functionality includes testing.
    - [ ] All tests pass
- [ ] New functionality has been documented.
    - [ ] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by yuye-aws** [comment]
Does anyone know why **Changelog Verifier** gets failed?

**Comment by navneet1v** [comment]
@yuye-aws you have to update the changelog.md file to make sure that changelog verifier is passing.

**Comment by yuye-aws** [comment]
> changelog.md

Thanks, I will update the file.

**Comment by yuye-aws** [comment]
@navneet1v All tests have passed my update to the change log file. Please help review my PR, thanks!

**Review by navneet1v — APPROVED** [review]

**Review by zhichao-aws — APPROVED** [review]

**Review by zane-neo — APPROVED** [review]

**Comment by yuye-aws** [comment]
Sure. This is my back PR: https://github.com/opensearch-project/neural-search/pull/600

**Pull request merged**
