### PR TITLE
Fix KNN SpaceType.getVectorSimilarityFunction renamed issue

### PR DESCRIPTION
**Pull request by chishui**
### Description
Knn repo `SpaceType.getVectorSimilarityFunction` has been rename to `SpaceType.getKnnVectorSimilarityFunction` by this [PR](https://github.com/opensearch-project/k-NN/pull/1781/) which caused :compileTestFixturesJava failure  https://github.com/opensearch-project/neural-search/actions/runs/9904116192/job/27602462802?pr=832

### Check List
- [ ] New functionality includes testing.
    - [ ] All tests pass
- [ ] New functionality has been documented.
    - [ ] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by chishui** [comment]
not ready, close for now

**Comment by yuye-aws** [comment]
It is nice of you to raise the PR. Can you please update the changelog and fix CI failures?

**Comment by navneet1v** [comment]
@chishui seems like there are changes in MLCommons that broke the build. 

```
Import org.opensearch.ml.client.MachineLearningNodeClient;
> Task :compileJava
                               ^
  bad class file: C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\org.opensearch\opensearch-ml-client\3.0.0.0-SNAPSHOT\886ef00577f1df5e128b402fd4c9ae6f772fd28f\opensearch-ml-client-3.0.0.0-SNAPSHOT.jar(/org/opensearch/ml/client/MachineLearningNodeClient.class)
    class file has wrong version 65.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:19: error: cannot access FunctionName
import org.opensearch.ml.common.FunctionName;
                               ^
  bad class file: C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\org.opensearch\opensearch-ml-client\3.0.0.0-SNAPSHOT\886ef00577f1df5e128b402fd4c9ae6f772fd28f\opensearch-ml-client-3.0.0.0-SNAPSHOT.jar(/org/opensearch/ml/common/FunctionName.class)
    class file has wrong version 65.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:20: error: cannot access MLInputDataset
import org.opensearch.ml.common.dataset.MLInputDataset;
                                       ^
  bad class file: C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\org.opensearch\opensearch-ml-client\3.0.0.0-SNAPSHOT\886ef00577f1df5e128b402fd4c9ae6f772fd28f\opensearch-ml-client-3.0.0.0-SNAPSHOT.jar(/org/opensearch/ml/common/dataset/MLInputDataset.class)
    class file has wrong version 65.0, should be [55](https://github.com/opensearch-project/neural-search/actions/runs/10002888226/job/27648933210?pr=834#step:4:56).0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:21: error: cannot access TextDocsInputDataSet
import org.opensearch.ml.common.dataset.TextDocsInputDataSet;
                                       ^
  bad class file: C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\org.opensearch\opensearch-ml-client\3.0.0.0-SNAPSHOT\886ef00[57](https://github.com/opensearch-project/neural-search/actions/runs/10002888226/job/27648933210?pr=834#step:4:58)7f1df5e128b402fd4c9ae6f772fd28f\opensearch-ml-client-3.0.0.0-SNAPSHOT.jar(/org/opensearch/ml/common/dataset/TextDocsInputDataSet.class)
    class file has wrong version 65.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:22: error: cannot access TextSimilarityInputDataSet
import org.opensearch.ml.common.dataset.TextSimilarityInputDataSet;
                                       ^
  bad class file: C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\org.opensearch\opensearch-ml-client\3.0.0.0-SNAPSHOT\886ef00577f1df5e128b402fd4c9ae6f772fd28f\opensearch-ml-client-3.0.0.0-SNAPSHOT.jar(/org/opensearch/ml/common/dataset/TextSimilarityInputDataSet.class)
    class file has wrong version 65.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:23: error: cannot access MLInput
import org.opensearch.ml.common.input.MLInput;
                                     ^
  bad class file: C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\org.opensearch\opensearch-ml-client\3.0.0.0-SNAPSHOT\886ef00577f1df5e128b402fd4c9ae6f772fd28f\opensearch-ml-client-3.0.0.0-SNAPSHOT.jar(/org/opensearch/ml/common/input/MLInput.class)
    class file has wrong version 65.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:24: error: cannot access MLOutput
import org.opensearch.ml.common.output.MLOutput;
                                      ^
  bad class file: C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\org.opensearch\opensearch-ml-client\3.0.0.0-SNAPSHOT\886ef00577f1df5e128b402fd4c9ae6f772fd28f\opensearch-ml-client-3.0.0.0-SNAPSHOT.jar(/org/opensearch/ml/common/output/MLOutput.class)
    class file has wrong version 65.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:25: error: cannot access ModelResultFilter
import org.opensearch.ml.common.output.model.ModelResultFilter;
                                            ^
  bad class file: C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\org.opensearch\opensearch-ml-client\3.0.0.0-SNAPSHOT\886ef00577f1df5e128b402fd4c9ae6f772fd28f\opensearch-ml-client-3.0.0.0-SNAPSHOT.jar(/org/opensearch/ml/common/output/model/ModelResultFilter.class)
    class file has wrong version 65.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:26: error: cannot access ModelTensor
import org.opensearch.ml.common.output.model.ModelTensor;
                                            ^
  bad class file: C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\org.opensearch\opensearch-ml-client\3.0.0.0-SNAPSHOT\886ef00577f1df5e128b402fd4c9ae6f772fd28f\opensearch-ml-client-3.0.0.0-SNAPSHOT.jar(/org/opensearch/ml/common/output/model/ModelTensor.class)
    class file has wrong version 65.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:27: error: cannot access ModelTensorOutput
import org.opensearch.ml.common.output.model.ModelTensorOutput;
                                            ^
  bad class file: C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\org.opensearch\opensearch-ml-client\3.0.0.0-SNAPSHOT\886ef00577f1df5e128b402fd4c9ae6f772fd28f\opensearch-ml-client-3.0.0.0-SNAPSHOT.jar(/org/opensearch/ml/common/output/model/ModelTensorOutput.class)
    class file has wrong version 65.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:28: error: cannot access ModelTensors
import org.opensearch.ml.common.output.model.ModelTensors;
                                            ^
  bad class file: C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\org.opensearch\opensearch-ml-client\3.0.0.0-SNAPSHOT\886ef00577f1df5e128b402fd4c9ae6f772fd28f\opensearch-ml-client-3.0.0.0-SNAPSHOT.jar(/org/opensearch/ml/common/output/model/ModelTensors.class)
    class file has wrong version 65.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:42: error: cannot find symbol
    private final MachineLearningNodeClient mlClient;
                  ^
  symbol:   class MachineLearningNodeClient
  location: class MLCommonsClientAccessor
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:216: error: cannot find symbol
    private MLInput createMLTextInput(final List<String> targetResponseFilters, List<String> inputText) {
            ^
  symbol:   class MLInput
  location: class MLCommonsClientAccessor
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:222: error: cannot find symbol
    private MLInput createMLTextPairsInput(final String query, final List<String> inputText) {
            ^
  symbol:   class MLInput
  location: class MLCommonsClientAccessor
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:227: error: cannot find symbol
    private List<List<Float>> buildVectorFromResponse(MLOutput mlOutput) {
                                                      ^
  symbol:   class MLOutput
  location: class MLCommonsClientAccessor
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:240: error: cannot find symbol
    private List<Map<String, ?>> buildMapResultFromResponse(MLOutput mlOutput) {
                                                            ^
  symbol:   class MLOutput
  location: class MLCommonsClientAccessor
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:2[58](https://github.com/opensearch-project/neural-search/actions/runs/10002888226/job/27648933210?pr=834#step:4:59): error: cannot find symbol
    private List<Float> buildSingleVectorFromResponse(final MLOutput mlOutput) {
                                                            ^
  symbol:   class MLOutput
  location: class MLCommonsClientAccessor
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:285: error: cannot find symbol
    private MLInput createMLMultimodalInput(final List<String> targetResponseFilters, final Map<String, String> input) {
            ^
  symbol:   class MLInput
  location: class MLCommonsClientAccessor
D:\a\neural-search\neural-search\src\main\java\org\opensearch\neuralsearch\ml\MLCommonsClientAccessor.java:38: error: cannot find symbol
@RequiredArgsConstructor
^
  symbol:   class MachineLearningNodeClient
  location: class MLCommonsClientAccessor
19 errors
```

**Comment by yuye-aws** [comment]
It's due to JDK version mismatch between ml-commons and neural search. From ml-commons, the expected JDK is 21. The version is thus 65. In neural-search, the version is 55 due to lower version JDK.

**Comment by yuye-aws** [comment]
This PR is ready for review: https://github.com/opensearch-project/neural-search/pull/835

**Comment by chishui** [comment]
covered in this PR https://github.com/opensearch-project/neural-search/pull/835

**Review by zhichao-aws — APPROVED** [review]

**Review by zane-neo — APPROVED** [review]

**Pull request merged**
