### PR TITLE
[chore]: bump developer guide java version

### PR DESCRIPTION
**Pull request by IanMenendez**
### Description
Bumped Java version in developer guide since it was outdated
 
### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by yuye-aws** [comment]
Can you also update the section title and description?

**Comment by IanMenendez** [comment]
Missed that. Need some rest haha

**Comment by yuye-aws** [comment]
Thank you. Since 2.x can still run on JDK 11 and 17, there is no need to backport this PR to 2.x.

**Review by yuye-aws — APPROVED** [review]
Looks good to me.

**Comment by martin-gaievski** [comment]
We can merge this one, CI is failing for some unrelated reason. @vibrantvarun can you please review?

**Comment by yuye-aws** [comment]
Pinging @zane-neo and @zhichao-aws for review

**Review by zhichao-aws — APPROVED** [review]
lgtm

**Pull request merged**
