### PR TITLE
Fixed unit tests after core added new assertion for remote metadata in index settings

### PR DESCRIPTION
**Pull request by martin-gaievski**
### Description
Fix failed unit tests https://github.com/opensearch-project/neural-search/actions/runs/8903989262/job/24477559143?pr=723.
Core has added new assert for index metadata in index settings.

### Check List
- [X] All tests pass
- [X] Commits are signed as per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by vibrantvarun** [comment]
Thanks Martin for raising the fix.

**Review by vibrantvarun — APPROVED** [review]

**Comment by martin-gaievski** [comment]
BWC and integTests will fail until https://github.com/opensearch-project/ml-commons/issues/2382 is merged by ml-commons, we need to look on results of `Gradle Check` tasks

**Comment by vibrantvarun** [comment]
No, BWC and integ tests will not fail now. ML commons has fixed that issue, It is just I am waiting for this PR CI checks to pass successfully and then I will close that bug.

**Comment by vibrantvarun** [comment]
Just had a word with Xun. The issue still prevails

**Comment by martin-gaievski** [comment]
> Just had a word with Xun. The issue still prevails

should we wait for that issue to be fixed first, and only then merge this PR?

**Comment by vibrantvarun** [comment]
We can merge this because on 2.x and 2.14 everything will pass. The issue is only when bwc version is 2.14 and current version is 3.0

**Review by navneet1v — APPROVED** [review]

**Pull request merged**
