### PR TITLE
Fixed code coverage report

### PR DESCRIPTION
**Pull request by martin-gaievski**
### Description
We need to re-enable cove coverage for this repo. At some point it got cancelled and stays like this for about 5-6 months.

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [X] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by martin-gaievski** [comment]
@peterzhuamazon can you please help with this issue?
With these changes upload of codecov is failing with 

```
[2024-11-06T01:12:03.492Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 429 - {"message":"Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1303s."}
```

https://github.com/opensearch-project/neural-search/actions/runs/11694952553/job/32570344238?pr=975#step:6:37

I was checking your PR https://github.com/codecov/feedback/issues/525 and copied changes from https://github.com/opensearch-project/dashboards-flow-framework/pull/401 to neural-search repo.

Before this change codecov action was failing with different issue: ```{"message":"Repository not found"}``` https://github.com/opensearch-project/neural-search/actions/runs/11616264178/job/32348813055?pr=971

**Comment by peterzhuamazon** [comment]
I added CODECOV_TOKEN to your secret now.

**Comment by peterzhuamazon** [comment]
You need to merge this PR and check in another PR to see.

**Comment by yuye-aws** [comment]
@martin-gaievski Can you confirm whether this is due to [flakey tests](https://github.com/opensearch-project/neural-search/actions/runs/11694952540/job/32569549572?pr=975)?

**Comment by martin-gaievski** [comment]
> @martin-gaievski Can you confirm whether this is due to [flakey tests](https://github.com/opensearch-project/neural-search/actions/runs/11694952540/job/32569549572?pr=975)?

it's different problem, not related to test logic.

**Comment by martin-gaievski** [comment]
> You need to merge this PR and check in another PR to see. There might be more tweaks tho.

thank you Peter, let us merge, we'll see how it goes

**Review by vibrantvarun — APPROVED** [review]

**Review by junqiu-lei — APPROVED** [review]

**Comment by martin-gaievski** [comment]
@peterzhuamazon it may be the case we need additional tweaking for neural search, could you please take a look?

While some of the code coverage report uploads were successful after this PR (for instance this run: https://github.com/opensearch-project/neural-search/actions/runs/11714216506/job/32683862354), for other PRs it's still failing with `Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 331s.` (https://github.com/opensearch-project/neural-search/actions/runs/11731912261/job/32684320733?pr=977#step:6:36).

**Pull request merged**
