### PR TITLE
[Backport to 2.x] Fixed exception for case when Hybrid query being wrapped into bool query

### PR DESCRIPTION
**Pull request by martin-gaievski**
### Description
Manual backport of commit https://github.com/opensearch-project/neural-search/commit/b3c73bdaae28629d9be4128afcf549c790070887 to 2.x (from https://github.com/opensearch-project/neural-search/pull/490)

### Check List
- [X] New functionality includes testing.
    - [X] All tests pass
- [X] New functionality has been documented.
    - [X] New functionality has javadoc added
- [X] Commits are signed as per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by navneet1v** [comment]
@martin-gaievski lets fix the failing workflows.

**Comment by martin-gaievski** [comment]
> @martin-gaievski lets fix the failing workflows.

working on this, there is a failed backport core PR that needs to be merged first https://github.com/opensearch-project/OpenSearch/pull/11281

**Comment by martin-gaievski** [comment]
@navneet1v fixed errors, we started upversion to 2.12 PR and few things were missing.

**Review by navneet1v — APPROVED** [review]

**Review by vamshin — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
